spring:
  cloud:
    gateway:
      routes:
        - id: api_server
          uri: http://api:8081
          predicates:
            - Path=/api/**
        - id: queue_server
          uri: http://message:9999
          predicates:
            - Path=/message/**