spring:
  cloud:
    gateway:
      routes:
        - id: api_server
          uri: http://localhost:8081
          predicates:
            - PATH=/api/**
        - id: queue_server
          uri: http://localhost:9999
          predicates:
            - PATH=/message/**