spring:
  cloud:
    gateway:
      routes:
        - uri: lb://api
          predicates:
            - Path=/api
#        - uri: http://localhost:9999
#          predicates:
#            - Path=/message
    loadbalancer:
      configurations: health-check
    discovery:
      client:
        simple: # SimpleDiscoveryClient to configure statically services
          instances:
            api:
              - secure: false
                port: 8081
                host: localhost
                serviceId: api
                instanceId: api-1
              - secure: false
                port: 8082
                host: localhost
                serviceId: api
                instanceId: api-2