spring:
  cloud:
    gateway:
      routes:
        - id: api_server
        - uri: lb://api-server
          predicates:
            - Path=/api/**
#        - uri: http://localhost:9999
#          predicates:
#            - Path=/message
      loadbalancer:
        configurations: health-check
        routes:
          - id: api-server
            uri: http://localhost:8081
          - id: api-server
            uri: http://localhost:8082