spring:
  datasource:
    url: jdbc:mysql://database:3306/authentication?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: devple
      password: 5ca51b52-9437-11ee-a5a1-0242ac170002
      minimum-idle: 1
      maximum-pool-size: 5
      initialization-fail-timeout: 20000
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
