spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/authentication?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: devple
    password: devple
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
